name: Java CI with Maven
on:
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/60s-jar-with-dependencies.jar
    - name: Bot Details
      id: bot-details
      uses: raven-actions/bot-details@v1

    - name: Bot Details outputs
      run: |
        echo "ID: ${{ steps.bot-details.outputs.id }}"
        echo "Slug name: ${{ steps.bot-details.outputs.slug }}"
        echo "Display name: ${{ steps.bot-details.outputs.name }}"
        echo "Email: ${{ steps.bot-details.outputs.email }}"
        echo "Name Email: ${{ steps.bot-details.outputs.name-email }}"
        echo "HTML URL: ${{ steps.bot-details.outputs.html-url }}"
        echo "API URL: ${{ steps.bot-details.outputs.api-url }}"
    - name: Commit files
      run: |
         git config --local user.email ${{ steps.bot-details.outputs.email }}
         git config --local user.name ${{ steps.bot-details.outputs.name }}
         git add .
         git commit -m "feat: update 60s"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: master
