name: Java CI with Maven
on:
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/60s-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "ten1fs@outlook.com"
         git config --local user.name "ten1fs"
         git add .
         git commit -m "feat: update 60s"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: master